[package]
name = "rust-translator-br"
version = "0.1.0"
edition = "2021"
description = "Um pequeno tradutor de palavras português -> inglês"
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive"] }